package com.drugstore.demo.modelo;
// Generated 15/05/2018 12:39:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {

	private int idcompra;
	private Cliente cliente;
	private String producto;
	private Integer cantidad;
	private Integer precio;
	private Set compraProductos = new HashSet(0);

	public Compra() {
	}

	public Compra(int idcompra, Cliente cliente) {
		this.idcompra = idcompra;
		this.cliente = cliente;
	}

	public Compra(int idcompra, Cliente cliente, String producto, Integer cantidad, Integer precio,
			Set compraProductos) {
		this.idcompra = idcompra;
		this.cliente = cliente;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precio = precio;
		this.compraProductos = compraProductos;
	}

	public int getIdcompra() {
		return this.idcompra;
	}

	public void setIdcompra(int idcompra) {
		this.idcompra = idcompra;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	public Set getCompraProductos() {
		return this.compraProductos;
	}

	public void setCompraProductos(Set compraProductos) {
		this.compraProductos = compraProductos;
	}

}
