package com.drugstore.demo.modelo;
// Generated 15/05/2018 12:39:00 PM by Hibernate Tools 4.0.0

/**
 * CompraProducto generated by hbm2java
 */
public class CompraProducto implements java.io.Serializable {

	private int idcompraproducto;
	private Compra compra;
	private Producto producto;

	public CompraProducto() {
	}

	public CompraProducto(int idcompraproducto, Compra compra, Producto producto) {
		this.idcompraproducto = idcompraproducto;
		this.compra = compra;
		this.producto = producto;
	}

	public int getIdcompraproducto() {
		return this.idcompraproducto;
	}

	public void setIdcompraproducto(int idcompraproducto) {
		this.idcompraproducto = idcompraproducto;
	}

	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

}
