package com.drugstore.demo.modelo;
// Generated 15/05/2018 12:39:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int idproducto;
	private Tipoproducto tipoproducto;
	private String nombre;
	private Integer cantidad;
	private Integer precio;
	private Set productoVentas = new HashSet(0);
	private Set compraProductos = new HashSet(0);

	public Producto() {
	}

	public Producto(int idproducto, Tipoproducto tipoproducto) {
		this.idproducto = idproducto;
		this.tipoproducto = tipoproducto;
	}

	public Producto(int idproducto, Tipoproducto tipoproducto, String nombre, Integer cantidad, Integer precio,
			Set productoVentas, Set compraProductos) {
		this.idproducto = idproducto;
		this.tipoproducto = tipoproducto;
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.precio = precio;
		this.productoVentas = productoVentas;
		this.compraProductos = compraProductos;
	}

	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	public Tipoproducto getTipoproducto() {
		return this.tipoproducto;
	}

	public void setTipoproducto(Tipoproducto tipoproducto) {
		this.tipoproducto = tipoproducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	public Set getProductoVentas() {
		return this.productoVentas;
	}

	public void setProductoVentas(Set productoVentas) {
		this.productoVentas = productoVentas;
	}

	public Set getCompraProductos() {
		return this.compraProductos;
	}

	public void setCompraProductos(Set compraProductos) {
		this.compraProductos = compraProductos;
	}

}
