package com.drugstore.demo.modelo;
// Generated 15/05/2018 12:39:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario implements java.io.Serializable {

	private int idtipousuario;
	private String nombre;
	private Set usuarios = new HashSet(0);

	public Tipousuario() {
	}

	public Tipousuario(int idtipousuario) {
		this.idtipousuario = idtipousuario;
	}

	public Tipousuario(int idtipousuario, String nombre, Set usuarios) {
		this.idtipousuario = idtipousuario;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	public int getIdtipousuario() {
		return this.idtipousuario;
	}

	public void setIdtipousuario(int idtipousuario) {
		this.idtipousuario = idtipousuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
