package com.drugstore.demo.modelo;
// Generated 15/05/2018 12:39:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto implements java.io.Serializable {

	private int idtipoproducto;
	private String nombre;
	private Set productos = new HashSet(0);

	public Tipoproducto() {
	}

	public Tipoproducto(int idtipoproducto) {
		this.idtipoproducto = idtipoproducto;
	}

	public Tipoproducto(int idtipoproducto, String nombre, Set productos) {
		this.idtipoproducto = idtipoproducto;
		this.nombre = nombre;
		this.productos = productos;
	}

	public int getIdtipoproducto() {
		return this.idtipoproducto;
	}

	public void setIdtipoproducto(int idtipoproducto) {
		this.idtipoproducto = idtipoproducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
