package com.drugstore.demo.modelo;
// Generated 15/05/2018 12:39:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private int idventa;
	private Usuario usuario;
	private String producto;
	private Integer precio;
	private Integer cantidad;
	private Set productoVentas = new HashSet(0);

	public Venta() {
	}

	public Venta(int idventa, Usuario usuario) {
		this.idventa = idventa;
		this.usuario = usuario;
	}

	public Venta(int idventa, Usuario usuario, String producto, Integer precio, Integer cantidad, Set productoVentas) {
		this.idventa = idventa;
		this.usuario = usuario;
		this.producto = producto;
		this.precio = precio;
		this.cantidad = cantidad;
		this.productoVentas = productoVentas;
	}

	public int getIdventa() {
		return this.idventa;
	}

	public void setIdventa(int idventa) {
		this.idventa = idventa;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Set getProductoVentas() {
		return this.productoVentas;
	}

	public void setProductoVentas(Set productoVentas) {
		this.productoVentas = productoVentas;
	}

}
